include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
  errors:
    invalid_annotation_target: ignore
    omit_local_variable_types: ignore
    one_member_abstracts: ignore

linter:
  rules:
    public_member_api_docs: false
    # prefer_dot_shorthands: true