include: package:very_good_analysis/analysis_options.yaml

analyzer:
  enable-experiment:
    - dot-shorthands
    
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    # prefer_dot_shorthands: true