// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zH--oGotcsskOjP7KdxrD8QaQdQu5ng',
    appId: '1:904587325956:web:f839264e9dc96b34923b51',
    messagingSenderId: '904587325956',
    projectId: 'periodility',
    authDomain: 'periodility.firebaseapp.com',
    storageBucket: 'periodility.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe1zYMymB_SH6TYzcfUQINpZkvM9YXHCg',
    appId: '1:904587325956:android:789af494b7d55a24923b51',
    messagingSenderId: '904587325956',
    projectId: 'periodility',
    storageBucket: 'periodility.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_F1XXTRDkWSPbpr4B0DeGyFZVf_9-u4',
    appId: '1:904587325956:ios:a58ea66ba44e9df8923b51',
    messagingSenderId: '904587325956',
    projectId: 'periodility',
    storageBucket: 'periodility.firebasestorage.app',
    iosBundleId: 'com.heed.periodility',
  );
}
